# Generated by Django 2.0.13 on 2019-05-14 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 50, 16, 262549)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 50, 16, 261510)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 50, 16, 260333)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 50, 16, 261993)),
        ),
    ]
