# Generated by Django 2.0.13 on 2019-05-06 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190506_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 3, 52, 38, 758922)),
        ),
    ]
